### ISSUE TITLE
Create button to jump from Gear Performance to Hooks, and back?

### ISSUE THREAD

**Issue by jimfellows-NOAA** [nwfsc-fram/pyFieldSoftware#143]
Add a button to allow users to jump directly from Gear Performance screen to the hooks screen in bottom left.

**Comment by jimfellows-NOAA** [comment]
Got button working, but it's messing up the "previous screen" tracking in the stateMachine.py file...

**Comment by jimfellows-NOAA** [comment]
Worked out the navigation for the new Hooks > button on the Gear Perf screen and have it updating accordingly with hooks.  For now its tucked right under the exclude button, might want to bump it down:

![image](https://user-images.githubusercontent.com/57507677/94966369-fd47dd80-04b1-11eb-8719-1fa69014e5cb.png)

Right now after going to the hooks screen from this button and clicking back, the app takes you back to the Drops screen.  Not sure if that's confusing or not, but it might be less confusing if we add in another button on the hooks screen that takes you to the Gear Performance screen, FYI @johnharms-NOAA

**Comment by johnharms-NOAA** [comment]
I see what you're saying about possible confusion about where the back "<" arrow would take you.  It might be a good idea to add a "Gear Perf." button on the hooks page for symmetry.  If so, having it as a proper button with a border around it might help as well.  I know we are a bit tight for space on that screen (and I'm not sure exactly how it renders on the small tablet screens), so we may have to play around a bit with where that button would go.

Probably the same general idea with the Hooks button on the Gear Perf. screen - a rectangular button like the others on that page, rather than just text on the screen might help newer users navigate the screens better.  And I agree that maybe bumping it down a notch on the page - level with "Major Tangle" would be good, in the same column space as the "Exclude" button.  I hadn't even thought about displaying the Gear Perf. results and Hook results in those buttons like you are showing above (to match how it is displayed on the Drops screen) but that is a good call!

**Comment by jimfellows-NOAA** [comment]
Here's how the button could look, still need to get it to hold to the bottom of the screen:

![image](https://user-images.githubusercontent.com/57507677/95512116-362df980-096d-11eb-93e3-ad9f5421d513.png)

I'll test out some places for a Gear Performance button on the hooks screen soon.

**Comment by johnharms-NOAA** [comment]
👍

**Comment by jimfellows-NOAA** [comment]
almost done here, just need to clean up some code.  Essentially the hooks and gear perf. labels that allow you to navigate forward from the drops screen have been re-created in the header of the gear perf and hooks screens so you can toggle between the two and see what's selected in each:

Gear Perf:
![image](https://user-images.githubusercontent.com/57507677/125145086-e5eaf000-e0d4-11eb-9f46-10ddc6f6bb45.png)


Hooks:
![image](https://user-images.githubusercontent.com/57507677/125145056-cf449900-e0d4-11eb-890b-4a70db495333.png)

Right now I'm hiding the Hooks > nav on gear performance if the angler isn't done fishing (the "At Surface" button hasn't been clicked), but I'd like to gray out/disable the button instead.

**Comment by jimfellows-NOAA** [comment]
Hiding the hooks nav button on gear performance if angler isn't done/at surface.  I can gray out if desired.

**Comment by johnharms-NOAA** [comment]
This seems to be working well - so far no problems navigating between the gear perf and hooks screens. I like the idea of hiding the hooks nav button until after At Surface is pressed (others may have different opinions).  One issue I am noticing though is that on the Drops screen, the Gear Perf  and Hooks abbreviations are not always showing up immediately; sometimes you have to completely back out of the site to the main splash page and go back in and then the codes will appear
