### ISSUE TITLE
H&L: FishSamplingEntryDialog: In disposition for tagged fish, do a global lookup to see if the tag number already exists in DB

### ISSUE THREAD

**Issue by ghost** [nwfsc-fram/pyFieldSoftware#43]

**Comment by jimfellows-NOAA** [comment]
First take of duplicate disposition tag id coded up on [hl-disp-tag-check](https://github.com/nwfsc-fram/pyFieldSoftware/tree/hl-disp-tag-check) branch:
![image](https://user-images.githubusercontent.com/57507677/92286749-bbc91000-eebc-11ea-8708-ec28b456e95d.png)

Things that might be good to do:
* Put the full, zero-padded tag id in message
* Allow duplicate records to insert into db, not completely prevent it

@johnharms-NOAA any preference on whether this little warning should allow the user to acknowledge the duplicate, and still insert the tag id anyway?

**Comment by johnharms-NOAA** [comment]
Jim - this looks great! Regarding your comment - yes, I think a warning message that the user could choose to override is preferable to an outright prohibition since it might be the previous entry of that tag number that was in error.  Also, in order for this to work as intended, we would need to make sure the boat's at-sea SQLite database includes all prior tag numbers from prior years. I'm not sure, but I think since we implemented HookLogger on the back deck in 2017 that the database only contained data from that year's sampling.
