### ISSUE TITLE
H&L: SpeciesReviewDialog: Change colors to gray for Bait Back, No Hook, etc., i.e. non-species items

### ISSUE THREAD

**Issue by ghost** [nwfsc-fram/pyFieldSoftware#82]

**Comment by johnharms-NOAA** [comment]
Possibly an "easy" issue.  Just need something to make it easier for the HM user to quickly visually differentiate between fish and non-fish entries when glancing at this screen.   "Graying out" the non-fish entries might not be the best approach because an inexperienced user might then interpret that is not being able to edit those entries.  Perhaps we could experiment around with different text colors - and if that isn't effective or makes it harder to read those entries in bright sunlight, maybe we try a light green background for the fish entries.  Using red, yellow, or gray backgrounds for any of this seem like bad ideas because all those colors have connotations like "error", "warning", "locked", etc. that we don't want to convey.

**Comment by jimfellows-NOAA** [comment]
Probably a bunch of options here, but could change the color of the X out button next to the entry to indicate what type of item has been selected.  Then we can easily keep that yellow highlighting for the selected entry.  Or could add an icon image to indicate the type, not sure if removing the "X" label will be counter-intuitive, hopefully I'm looking at the right screen in hook matrix:

![image](https://user-images.githubusercontent.com/57507677/92501136-fbd90d00-f1b2-11ea-883f-77e0aa2e88ae.png)

Could even identify what type of organism is selected based off the taxonomy, adding text below just so i don't lose it:

```sql
WITH bony 
AS(
SELECT 
		taxonomy_ID
		,taxonomic_level
		,scientific_name
		,common_name_1
		,parent_taxonomy_id
		,1 RecursiveOrder  
FROM 	taxonomy_lu  
WHERE 	scientific_name = 'Osteichthyes'
UNION ALL
SELECT  
		t.taxonomy_id
		,t.taxonomic_level
		,t.scientific_name
		,t.common_name_1
		,t.parent_taxonomy_id
		,RecursiveOrder+1 RecursiveOrder  
FROM 	taxonomy_lu t
JOIN 	bony ON t.parent_taxonomy_id = bony.taxonomy_id
)

select * from bony

```

**Comment by johnharms-NOAA** [comment]
Yes, that's the right screen in HM. Now that I look at the software, I'm recalling what the need was here, and I'd forgotten that the field highlights in yellow to show which field you're in and agree that altering the highlighting might not be the right approach. I think the main issue for users was that all the text looks very homogeneous from top to bottom. Though I like that fish icon, I also agree that it might not be intuitive that it still represents a delete function. How about this:

1) For the headers ("Hook 5", "Hook 4", etc.):  underscore and center them over the white field. If that looks too busy, could always shrink the font by one size

2) For fish entries, text appears in green and bolded.

**Comment by jimfellows-NOAA** [comment]
Sounds like a good plan.  I've added in the green bold highlighting, still working on centering the Hook labels, its a little finicky:

![image](https://user-images.githubusercontent.com/57507677/92544595-25218980-f203-11ea-9ed7-a8264b42af2f.png)

**Comment by jimfellows-NOAA** [comment]
Ok, here's with labels centered and underlined:

![image](https://user-images.githubusercontent.com/57507677/92605214-4f586300-f266-11ea-87c8-83d7bdf80c4a.png)

**Comment by jimfellows-NOAA** [comment]
Closing issue.  Pulling non-species list from DB this time.  Fix set on develop-hlmatrix.
